language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  - "pypy"

# command to install dependencies
install:
  - pip install -r requirements.txt codecov

# command to run tests
script: python ./test_markdown_edit.py

after_success: python -m coverage run --source=markdown_editor test_markdown_edit.py && codecov

